const mongoose = require('mongoose')
const Schema = mongoose.Schema

// Subesquema para informações comuns a todas as disciplinas
// const DisciplinaSchema = {
//     nome: { type: String, required: true },
//     bim1: { type: String, required: true },
//     bim2: { type: String, required: true },
//     bim3: { type: String, required: true },
//     bim4: { type: String, required: true },
//     final: { type: String, required: true },
//     conselho: { type: String, required: true },
//     aulas: { type: Number, required: true },
//     faltas: { type: Number, required: true },
//     frequencia: { type: Number, required: true }
// };


// const PrimeiraSerieSchema = {
//     nome: { type: String, required: true },
//     portugues: [DisciplinaSchema],
//     ingles: [DisciplinaSchema],
//     matematica: [DisciplinaSchema],
//     edfisica: [DisciplinaSchema],
//     espanhol: [DisciplinaSchema],
//     arte: [DisciplinaSchema],
//     filosofia: [DisciplinaSchema],
//     sociologia: [DisciplinaSchema],
//     ad: [DisciplinaSchema],
//     bd: [DisciplinaSchema],
//     finf: [DisciplinaSchema],
//     pa: [DisciplinaSchema],
//     gcwI: [DisciplinaSchema],
//     iwI: [DisciplinaSchema]
// };

// const SegundaSerieSchema = {
//     nome: { type: String, required: true },
//     portugues: [DisciplinaSchema],
//     ingles: [DisciplinaSchema],
//     matematica: [DisciplinaSchema],
//     edfisica: [DisciplinaSchema],
//     historia: [DisciplinaSchema],
//     geografia: [DisciplinaSchema],
//     fisica: [DisciplinaSchema],
//     quimica: [DisciplinaSchema],
//     biologia: [DisciplinaSchema],
//     gcwII: [DisciplinaSchema],
//     iwII: [DisciplinaSchema],
//     udi: [DisciplinaSchema],
//     ddmI: [DisciplinaSchema],
//     swI: [DisciplinaSchema]
// };

// const TerceiraSerieSchema = {
//     nome: { type: String, required: true },
//     portugues: [DisciplinaSchema],
//     ingles: [DisciplinaSchema],
//     matematica: [DisciplinaSchema],
//     historia: [DisciplinaSchema],
//     geografia: [DisciplinaSchema],
//     fisica: [DisciplinaSchema],
//     quimica: [DisciplinaSchema],
//     biologia: [DisciplinaSchema],
//     ddmII: [DisciplinaSchema],
//     swII: [DisciplinaSchema],
//     acedig: [DisciplinaSchema],
//     etica: [DisciplinaSchema],
//     tcc: [DisciplinaSchema],
//     si: [DisciplinaSchema]
// };

const Boletim = new Schema({
    usuario: {
        type: Schema.Types.ObjectId,
        ref: 'usuarios',
        required: true
    },
    serie1: {
        nome: { type: String, required: true },
        materia01: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia02: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia03: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia04: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia05: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia06: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia07: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia08: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia09: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia10: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia11: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia12: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia13: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia14: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        }
    },
    serie2: {
        nome: { type: String, required: true },
        materia01: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia02: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia03: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia04: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia05: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia06: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia07: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia08: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia09: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia10: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia11: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia12: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia13: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia14: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        }
    },
    serie3: {
        nome: { type: String, required: true },
        materia01: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia02: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia03: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia04: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia05: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia06: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia07: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia08: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia09: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia10: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia11: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia12: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia13: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        },
        materia14: {
            nome: { type: String, required: true },
            bim1: { type: String, required: true },
            bim2: { type: String, required: true },
            bim3: { type: String, required: true },
            bim4: { type: String, required: true },
            final: { type: String, required: true },
            conselho: { type: String, required: true },
            aulas: { type: Number, required: true },
            faltas: { type: Number, required: true },
            frequencia: { type: Number, required: true }
        }
    }
})

// Existem 2 parâmetros: o primeiro refere-se ao nome da collection (tabela). O segundo refere-se ao schema da collection (dados que farão parte da collection(documents))
mongoose.model('boletins', Boletim)

// {
// "_id": {
//     "$oid": "654aa98e25915d0c42b65953"
// },
// "usuario": {
//     "$oid": "652852ec1a889b20f082dcf7"
// },
// "serie1":{
//     "nome": "1ª Série",
//     "materia01": {
//         "nome": "LÍNGUA PORTUGUESA, LITERATURA E COMUNICAÇÃO PROFISSIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 10,
//         "frequencia": "90%"
//     },
//     "materia02": {
//         "nome": "LÍNGUA ESTRANGEIRA MODERNA - INGLÊS E COMUNICAÇÃO PROFISSIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia03": {
//         "nome": "MATEMÁTICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia04": {
//         "nome": "EDUCAÇÃO FÍSICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia05": {
//         "nome": "LÍNGUA ESTRANGEIRA MODERNA - ESPANHOL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia06": {
//         "nome": "ARTE",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia07": {
//         "nome": "FILOSOFIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia08": {
//         "nome": "SOCIOLOGIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia09": {
//         "nome": "ARTE DIGITAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia10": {
//         "nome": "BANCO DE DADOS",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia11": {
//         "nome": "FUNDAMENTOS DA INFORMÁTICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia12": {
//         "nome": "PROGRAMAÇÃO E ALGORITMOS",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia13": {
//         "nome": "GESTÃO DE CONTEÚDO WEB I",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia14": {
//         "nome": "INTERFACES WEB I",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     }
// },
// "serie2":{
//     "nome": "2ª Série",
//     "materia01": {
//         "nome": "LÍNGUA PORTUGUESA, LITERATURA E COMUNICAÇÃO PROFISSIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 10,
//         "frequencia": "90%"
//     },
//     "materia02": {
//         "nome": "LÍNGUA ESTRANGEIRA MODERNA - INGLÊS E COMUNICAÇÃO PROFISSIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia03": {
//         "nome": "MATEMÁTICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia04": {
//         "nome": "EDUCAÇÃO FÍSICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia05": {
//         "nome": "HISTÓRIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia06": {
//         "nome": "GEOGRAFIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia07": {
//         "nome": "FÍSICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia08": {
//         "nome": "QUÍMICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia09": {
//         "nome": "BIOLOGIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia10": {
//         "nome": "GESTÃO DE CONTEÚDO WEB II",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia11": {
//         "nome": "INTERFACES WEB II",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia12": {
//         "nome": "USABILIDADE E DESIGN DE INTERAÇÃO",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia13": {
//         "nome": "DESENVOLVIMENTO PARA DISPOSITIVOS MÓVEIS I",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia14": {
//         "nome": "SISTEMAS WEB I",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     }
// },
// "serie3":{
//     "nome": "3ª Série",
//     "materia01": {
//         "nome": "LÍNGUA PORTUGUESA, LITERATURA E COMUNICAÇÃO PROFISSIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 10,
//         "frequencia": "90%"
//     },
//     "materia02": {
//         "nome": "LÍNGUA ESTRANGEIRA MODERNA - INGLÊS E COMUNICAÇÃO PROFISSIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia03": {
//         "nome": "MATEMÁTICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia04": {
//         "nome": "HISTÓRIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia05": {
//         "nome": "GEOGRAFIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia06": {
//         "nome": "FÍSICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia07": {
//         "nome": "QUÍMICA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia08": {
//         "nome": "BIOLOGIA",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia09": {
//         "nome": "DESENVOLVIMENTO PARA DISPOSITIVOS MÓVEIS II",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia10": {
//         "nome": "SISTEMAS WEB II",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia11": {
//         "nome": "ACESSIBILIDADE DIGITAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia12": {
//         "nome": "ÉTICA E CIDADANIA ORGANIZACIONAL",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia13": {
//         "nome": "PLANEJAMENTO E DESENVOLVIMENTO DO TRABALHO DE CONCLUSÃO DE CURSO (TCC) EM INFORMÁTICA PARA INTERNET",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     },
//     "materia14": {
//         "nome": "SEGURANÇA DA INFORMAÇÃO",
//         "bim1": "MB",
//         "bim2": "MB",
//         "bim3": "MB",
//         "bim4": "MB",
//         "final": "MB",
//         "conselho": "MB",
//         "aulas": 100,
//         "faltas": 0,
//         "frequencia": "100%"
//     }
// }
// }